let allergies = {
    "Dairy": [
        "Acidophilus Milk",
        "Ammonium Caseinate",
        "Butter",
        "Butter Esters",
        "Butter Fat",
        "Butter Oil",
        "Butter Solids",
        "Buttermilk",
        "Buttermilk Powder",
        "Calcium Caseinate",
        "Casein",
        "Caseinate",
        "Cheese",
        "Condensed Milk",
        "Cottage Cheese",
        "Cream",
        "Curds",
        "Custard",
        "Delactosed Whey",
        "Demineralized Whey",
        "Dry Milk Powder",
        "Dry Milk Solids",
        "Evaporated Milk",
        "Ghee",
        "Goat Cheese",
        "Goat Milk",
        "Half & Half",
        "Hydrolyzed Casein",
        "Hydrolyzed Milk Protein",
        "Iron Caseinate",
        "Lactalbumin",
        "Lactoferrin",
        "Lactoglobulin",
        "Lactose",
        "Lactulose",
        "Low-Fat Milk",
        "Magnesium Caseinate",
        "Malted Milk",
        "Milk",
        "Milk Derivative",
        "Milk Fat",
        "Milk Powder",
        "Milk Protein",
        "Milk Solids",
        "Natural Butter Flavor",
        "Nonfat Milk",
        "Nougat",
        "Paneer",
        "Potassium Caseinate",
        "Pudding",
        "Recaldent",
        "Rennet Casein",
        "Sheep Milk",
        "Sheep Milk Cheese",
        "Skim Milk",
        "Sodium Caseinate",
        "Sour Cream",
        "Sour Milk Solids",
        "Sweetened Condensed Milk",
        "Sweet Whey",
        "Whey",
        "Whey Powder",
        "Whey Protein Concentrate",
        "Whey Protein Hydrolysate",
        "Whipped Cream",
        "Whipped Topping",
        "Whole Milk",
        "Yogurt",
        "Zinc Caseinate",
    ],
    mandiAllergies = [
    'dairy',
    'peanuts',
    'alfalfa',
    'clover',
    'peas',
    'lentils',
    'lupins',
    'mesquite',
    'carob',
    'soybeans',
    'tamarind',
    'wisteria',
    'pinto bean',
    'kidney bean',
    'green bean',
    'fava bean',
    'lima bean',
    'chickpeas',
    'beans',
    'melon',
    'banana',
    'seafood',
  ]
}